# SPDX-License-Identifier: MIT

name: Pylint

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pipenv
    - name: Install package
      run: |
        pipenv install --dev --editable .
    - name: Analysing the code with pylint
      run: |
        pipenv run pylint src/snap_to_bucket
